max_threads: 6

data:
  base_root: "data"
  dirs:
    raw: "raw"
    references: "references"
    trimmed: 'trimmed'

workflow:
  base_root: "workflow"
  dirs:
    rules: "rules"
    scripts: "scripts"
    lib: "lib"
    envs: 'envs'

output:
  base_root: "output"
  dirs:
    mapped: 'mapped'
    meth_call: 'methylation_calling'

qc:
  base_root: "QC"
  dirs:
    mapping: 'mapping'
    raw: 'raw'
    trimmed: 'trimmed'
    mbias: 'mbias'
    bam_stat: 'flagstat'
  plots:
    - duplicates_rates
    - mapping_rates
    - total_reads

suffix:
  fasta: 'fasta'
  fastq: 'fastq'
  compressed: 'gz'

scripts:
  qc:
    base_root: 'QC'
    fetch_read_counts: 'fetch_reads_count.py'

ref:
  genome: 
    link: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/GRCh38.primary_assembly.genome.fa.gz"
    file_name: "homo_GRCh38_ref.fa"